### ISSUE TITLE
Port r2-retdec to cutter

### ISSUE THREAD

**Issue by Maijin** [radareorg/cutter-plugins#1]
https://github.com/jpenalbae/r2-scripts/blob/master/decompiler/decompile.js from @jpenalbae as another pseudo-code panel capability see release https://github.com/avast-tl/retdec.

see https://asciinema.org/a/20904

![image](https://user-images.githubusercontent.com/1408600/33819640-c14aa14e-de4b-11e7-928a-270a3a7cc826.png)

**Comment by ITAYC0HEN** [comment]
Done :)
https://github.com/avast/retdec-r2plugin/tree/master/cutter-plugin
